name: LaTeX Build  # Název workflow

on:
  push:
    branches:
      - main  # Spustí se při pushi do main
    paths:
      - 'src/**'   # pouze změny ve složce src
  pull_request:
    branches:
      - main  # Spustí se při PR do main
    paths:
      - 'src/**'   # pouze změny ve složce src

permissions:
  contents: write  # Potřebné pro pushnutí PDF zpět do repo

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Stáhne repo do runneru

    - name: Compile LaTeX with latexmk
      run: |
        docker run --rm \
        -v ${{ github.workspace }}:/workspace \
        -w /workspace \
        texlive/texlive:latest \
        bash -c "
        apt-get update &&
        apt-get install -y fontconfig fonts-crosextra-carlito inkscape &&
        mkdir -p /workspace/output &&
        chmod -R 777 /workspace/output &&
        chmod -R 777 /workspace/src &&
        fc-cache -f &&
        latexmk -xelatex -interaction=nonstopmode --shell-escape \
        -output-directory=/workspace/output \
        /workspace/src/semestralni_prace.tex
        "

    - name: Commit and push compiled PDF
      run: |
        git config --global user.name "github-actions[bot]"  # Nastavení identity
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        timestamp=$(date "+%d-%m-%Y_%H%M")                  # Timestamp pro verzi
        cp output/semestralni_prace.pdf Verze/semestralni_prace_"${timestamp}".pdf  # Kopie
        git add Verze/semestralni_prace_"${timestamp}".pdf  # Přidání do git
        git commit -m "Automated PDF compilation and deployment [skip ci]"  # Commit
        git push origin main  # Push zpět do main